print('Welcome to the Choices Saga!\n')
print('You are about to start your journey but before you do we need to know a few things about you.\n')
print('Please tell us your name:\n')
playerName = input()
print('Welcome ' + playerName + '!\n\nCould you tell us which of these languages you know:')
print('Please type the languages exactly with commas between if more than one): English, Swedish, Estonian')
playerLanguages = input()
print('So you know: ' + playerLanguages + '.\n')
